name: Warrior Gym Watcher

on:
  schedule:
    # trainers should be updating the data every hour or so.
    # to remain accurate, want to run every 20 mins
    # (minute hour day month weekday) for reference
    - cron: "*/20 * * * *"
  workflow_dispatch: # allow manual triggers for testing purposes

jobs:
  scrape-and-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Install Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install Dependencies
        # install src package and all dependencies from pyproject.toml
        run: poetry install --no-interaction

      - name: Run Scraper
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: poetry run python run_watcher.py
